export const language = {
    polish: {
        lang: 'PL',
        iconPath: '/icons/pl.png',
        searchInput: "Szukaj narzędzi",
        about: "O projekcie",
        help: "Pomóż nam",
        login: "Zaloguj",
        priceFree: "Darmowy",
        pricePaid: "Płatny",
        designLabel: "Projektowanie",
        home: "Lista",
        mainMsg: "Cały czas pracujemy żeby usprawnić Helpfool! ",
        getItHere: "Przejdź",
        About: {
            about: "O projekcie",
            aboutMessage: "Praca programisty nie należy do najłatwiejszych, często wymaga od nas przekopywania się przez tony internetu w poszukiwaniu potrzebnych do prototypowania czy tworzenia aplikacji bibliotek, grafik, ikon, filmów itd. Tak, mnie też to zawsze męczyło, często jak znalazłem jakąś przydatną stronę to w końcu i tak ginęła i musiałem jej szukać na nowo. A gdyby tak nie musieć spędzać tony czasu na szukaniu tego co trzeba? Właśnie dlatego powstało Helpfool, żeby unikać tracenia czasu na szukanie, bo tutaj wszystko jest pod ręką, zawsze.",
            resourcesLabel: "Wykorzystane zasoby",
            resourcesText: "Cała strona jest darmowa i zostały do niej wykorzystane darmowe zasoby, takie jak ikony czy spis linków z darmowymi stronami które są główną zawartością tej strony. Wszystko możecie znaleźć pod podanymi linkami.",
            resourceIcons: "Ikony",
            resourceSource: "Źródło",
            resource: "Lista zasobów",
        },
        Help: {
            helpLabel: "Chcę pomóc!",
            helpWithSite: "Cały projekt jest otwarto źródłowy więc jeśli coś nie działa, masz pomysła jak coś usprawnić, lub chcesz pomóc w rozwoju to masz otwarte drzwi!",
            helpWithTranslation: "Dostępne są tylko 2 języki - Polski i Angielski. Jeśli jesteś w stanie przetłumaczyć treść na jakiś inny to się nie krępuj.",
            buttonGit: "Projekt na githubie",
            buttonTrello: "Lista Trello",
        },
        Admin: {
            adminLabel: "Panel Administratora",
            logout: "Wyloguj",
            addBtt: "Dodaj nowe narzędzie",
            previewBtt: "Podgląd",
            proposedBtt: "Przeglądaj proponowane",
            category: "Kategoria",
            name: "Nazwa",
            link: "Adres strony",
            price: "Darmowy",
            descPL: "Opis po polsku",
            descENG: "Opis po angielsku",
            tags: "Tagi",
            submitBtt: "Dodaj",
            errCategory: "Nie wybrano kategorii",
            errLink: "Niepoprawny link",
            errDescPL: "Brak polskiego opisu",
            errDescEng: "Brak angielskiego opisu",
            errName: "Brak nazwy",
            toolSent: "Udało się wysłać",
            Select: {
                uiGraphics: "UI Graphics",
                fonts: "Czcionki",
                colors: "Kolory",
                icons: "Ikony",
                logos: "Loga",
                favicons: "Favikony",
                iconFonts: "Czcionki ikonowe",
                stockPhotos: "Zdjęcia",
                stockVideos: "Filmy",
                music: "Muzyka i efekty dźwiękowe",
                vectors: "Wektory i kliparty",
                webTemplates: "Szablony HTML i CSS",
                cssFrameworks: "Frameworki CSS",
                cssMethodologies: "Metodologie CSS",
                cssAnimations: "Animacje CSS",
                jsAnimations: "Animacje JavaScript",
                uiComponents: "Komponenty UI",
                reactUiLibs: "Biblioteki UI React",
                vueUiLibs: "Biblioteki UI Vue",
                angularUiLibs: "Biblioteki UI Angular",
                svelteUiLibs: "Biblioteki UI Svelte",
                reactNativeUiLibs: "Biblioteki UI React Native",
                designSystems: "Systemy projektowania",
                designTools: "Narzędzia do projektowania online",
                downloadDesignTools: "Pobieralne narzędzia do projektowania",
                designInspirations: "Inspiracje projektowe",
                imgCompression: "Kompresja obrazów",
                chromeExtensions: "Rozszerzenia do chrome",
                others: "Inne",
            },
        }
    },
    english: {
        lang: 'ENG',
        iconPath: '/icons/eng.png',
        searchInput: "Search tool",
        about: "About",
        help: "Help us",
        login: "Log in",
        priceFree: "Free",
        pricePaid: "Paid",
        designLabel: "Design",
        home: "Home",
        mainMsg: "We are still working to improve Helpfool! ",
        getItHere: "Get it here",
        About: {
            about: "About project",
            aboutMessage: "Praca programisty nie należy do najłatwiejszych, często wymaga od nas przekopywania się przez tony internetu w poszukiwaniu potrzebnych do prototypowania czy tworzenia aplikacji bibliotek, grafik, ikon, filmów itd. Tak, mnie też to zawsze męczyło, często jak znalazłem jakąś przydatną stronę to w końcu i tak ginęła i musiałem jej szukać na nowo. A gdyby tak nie musieć spędzać tony czasu na szukaniu tego co trzeba? Właśnie dlatego powstało Helpfool, żeby unikać tracenia czasu na szukanie, bo tutaj wszystko jest pod ręką, zawsze.",
            resourcesLabel: "Used resources",
            resourcesText: "Cała strona jest darmowa i zostały do niej wykorzystane darmowe zasoby które możecie znaleźć pod tymi linkami.",
            resourceIcons: "Icons",
            resourceSource: "Source",
            resource: "Resource list",
        },
        Help: {
            helpLabel: "I want to help!",
            helpWithSite: "Cały projekt jest otwrto źródłowy więc jeśli coś nie działa, masz pomysła jak coś usprawnić, lub chcesz pomóc w rozwoju to masz otwarte drzwi!",
            helpWithTranslation: "Dostępne są tylko 2 języki - Polski i Angielski. Jeśli jesteś w stanie przetłumaczyć treść na jakiś inny to się nie krępuj.",
            buttonGit: "Github project",
            buttonTrello: "Trello list",
        },
        Admin: {
            adminLabel: "Administrator Panel",
            logout: "Logout",
            addBtt: "Add new tool",
            previewBtt: "Preview",
            proposedBtt: "Watch proposed",
            category: "Category",
            name: "Name",
            link: "Site address",
            price: "Free",
            descPL: "Description in polish",
            descENG: "Description in english",
            tags: "Tags",
            submitBtt: "Add",
            errCategory: "Category has not been selected",
            errLink: "Invalid link",
            errDescPL: "No polish description",
            errDescEng: "No english description",
            errName: "No name",
            toolSent: "Successfully sent",
            Select: {
                uiGraphics: "UI Graphics",
                fonts: "Fonts",
                colors: "Colors",
                icons: "Icons",
                logos: "Logos",
                favicons: "Favicons",
                iconFonts: "Icon Fonts",
                stockPhotos: "Stock Photos",
                stockVideos: "Stock Videos",
                music: "Stock Music & Sound Effects",
                vectors: "Vectors & Clipart",
                webTemplates: "HTML & CSS Templates",
                cssFrameworks: "CSS Frameworks",
                cssMethodologies: "CSS Methodologies",
                cssAnimations: "CSS Animations",
                jsAnimations: "Javascript Animations",
                uiComponents: "UI Components & Kits",
                reactUiLibs: "React UI Libraries",
                vueUiLibs: "Vue UI Libraries",
                angularUiLibs: "Angular UI Libraries",
                svelteUiLibs: "Svelte UI Libraries",
                reactNativeUiLibs: "React Native UI Libraries",
                designSystems: "Design Systems & Style Guides",
                designTools: "Online Design Tools",
                downloadDesignTools: "Downloadable Design Software",
                designInspirations: "Design Inspiration",
                imgCompression: "Image Compression",
                chromeExtensions: "Chrome Extensions",
                others: "Others",
            }
        }
    }
};